### PR TITLE
Added strict comparison to null

### PR DESCRIPTION
**Pull request by michaeltintiuc**
For issue #196 I've noticed that there are instances of `is_null` in your code base. If you'd like I could create a separate PR for that.

### CODE REVIEW

**Comment by aik099** [comment]
Please rebase so that I can see on Travis CI if test suite is passing.

**Comment by michaeltintiuc** [comment]
@aik099 Done, let me know

**Comment by aik099** [comment]
Looks good. Merging, thanks @michaeltintiuc .

Yes, you can send another PR to fix other occurrences of `null` comparison done in non-strict manner.

**Comment by michaeltintiuc** [comment]
Thanks @aik099 will do so asap

**Pull request merged**
